#!/bin/bash
# Generates .actrc file with the correct Docker socket path for your system

set -e

# Get Docker socket URI from current context (includes unix:// prefix)
DOCKER_SOCKET_URI=$(docker context inspect --format '{{.Endpoints.docker.Host}}' 2>/dev/null)

if [[ -z "$DOCKER_SOCKET_URI" ]]; then
    # Fallback to common locations
    if [[ -S "/var/run/docker.sock" ]]; then
        DOCKER_SOCKET_URI="unix:///var/run/docker.sock"
    elif [[ -S "$HOME/.docker/desktop/docker.sock" ]]; then
        DOCKER_SOCKET_URI="unix://$HOME/.docker/desktop/docker.sock"
    else
        echo "Error: Could not find Docker socket. Make sure Docker is running."
        exit 1
    fi
fi

# Extract path from URI to verify socket exists
DOCKER_SOCKET_PATH=$(echo "$DOCKER_SOCKET_URI" | sed 's|unix://||')

if [[ ! -S "$DOCKER_SOCKET_PATH" ]]; then
    echo "Error: Docker socket not found at $DOCKER_SOCKET_PATH"
    exit 1
fi

# Verify Docker is accessible
if ! docker info >/dev/null 2>&1; then
    echo "Error: Cannot connect to Docker. Make sure Docker is running."
    exit 1
fi

# Generate .actrc
cat > .actrc << EOF
# Default act configuration (generated by setup-act.sh)
# Use medium-sized Ubuntu image (good balance of speed vs compatibility)
-P ubuntu-latest=catthehacker/ubuntu:act-latest

# Docker socket URI
--container-daemon-socket $DOCKER_SOCKET_URI
EOF

echo "Created .actrc with Docker socket: $DOCKER_SOCKET_URI"
echo ""
echo "You can now run tests with:"
echo "  ./bin/act -j test-validation"
echo "  ./bin/act -j test-decrypt"